name: Generate ICS

# runs on push to main branch only when changes are in crons/
on:
  schedule:
    # runs on 1st day of every 3 month at 00:00
    - cron: "0 0 1 1-12/3 *"
  push:
    branches: [ "main" ]
    paths:
      - 'crons/**'


jobs:
  setup-and-run-script:
  # uses latest ubuntu
    runs-on: ubuntu-latest
    # allows for write permissions on runner
    permissions:
      contents: write

    # clones the repo into the runner
    steps:
    - uses: actions/checkout@v4

    # installs the uv into runner
    - name: Install uv
      uses: astral-sh/setup-uv@v3

    # install Python 3.12
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    # reads pyproject.toml and installs the dependencies
    - name: Install dependencies
      run: |
        uv sync

    # runs the script generate-ics,py using the .venv
    - name: Run Script
      run: |
        uv run generate-ics.py

    # checks to see if calendar.ics is changed and adds any logs in generate-ics-action.log commit and pushes it
    - name: Commit and push calendar.ics
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "[actions]: regenerate calendar.ics"
        file_pattern: "public/calendar.ics logs/generate-ics-action.log"

    # add for debugging purposes
    - name: Debug
      run: |
        ls -la crons/
        git status
